device:
    MACAddress: 2C-AC-44-04-97-01
    ip: 192.168.1.200
    port: 2022
    antennas:
        num: 4
        map:
            1: true
    verbose: false
    frequency:
        interval: 1_000 # ms
        specs:
            -   band: 21
                minN: 0
                maxN: 34
